### ISSUE TITLE
Error při tvoření nových tasklocationů

### ISSUE THREAD

**Issue by lukx1** [lukx1/Backupper#18]
Vytvoření nového task locationu na stránce [http://localhost:3393/AdminTasks/NewTaskLocation?id=19](url)  způsobí exception na serveru

Exception:
```csharp
System.Data.Entity.Infrastructure.DbUpdateConcurrencyException occurred
  HResult=0x80131501
  Message=Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.
  Source=EntityFramework
  StackTrace:
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at Server.Models.Admin.NewEditTaskLocationsModel.Save() in E:\Projects\Programming\Workspace\C#\Backupper\Core\Server\Server\Models\Admin\NewEditTaskLocationsModel.cs:line 80
   at Server.Controllers.AdminTasksController.NewTaskLocation(NewEditTaskLocationsModel model) in E:\Projects\Programming\Workspace\C#\Backupper\Core\Server\Server\Controllers\AdminTasksController.cs:line 173
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

Inner Exception 1:
OptimisticConcurrencyException: Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.

```

Error obrazovka serveru:
`Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=472540 for information on understanding and handling optimistic concurrency exceptions.`

**Comment by donutX3** [comment]
novy task location byl nastaven na State.Modified a proto SaveChanges hazelo tuhle chybu jiz funguje
