### ISSUE TITLE
NullReferenceException v  Tasks.cshtml

### ISSUE THREAD

**Issue by lukx1** [lukx1/Backupper#19]
Jak reprodukovat:
Na novém tasků, který má jeden tasklocation přiřaďte jeden existující čas

Exception:
```csharp
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at ASP._Page_Views_AdminTasks_Tasks_cshtml.Execute() in E:\Projects\Programming\Workspace\C#\Backupper\Core\Server\Server\Views\AdminTasks\Tasks.cshtml:line 17
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.StartPage.RunPage()
   at System.Web.WebPages.StartPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult)

```

**Comment by lukx1** [comment]
Snížena závažnost, jelikož čas je přidán a funkční, ale exception je stejně hozen.

**Comment by donutX3** [comment]
Opraveno
