### ISSUE TITLE
Exception po uložení credential

### ISSUE THREAD

**Issue by lukx1** [lukx1/Backupper#21]
Nastal po vytvoření nového credential na [http://localhost:3393/AdminLocationCredentials](url)

Exception v AdminBaseController.cs
```
System.InvalidCastException occurred
  HResult=0x80004002
  Message=Unable to cast object of type 'Server.Controllers.AdminPowerController' to type 'Server.Controllers.AdminBaseController'.
  Source=Server
  StackTrace:
   at Server.Controllers.AdminSecAttribute.OnAuthentication(AuthenticationContext filterContext) in E:\Projects\Programming\Workspace\C#\Backupper\Core\Server\Server\Controllers\AdminBaseController.cs:line 79
   at System.Web.Mvc.ControllerActionInvoker.InvokeAuthenticationFilters(ControllerContext controllerContext, IList`1 filters, ActionDescriptor actionDescriptor)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__19(AsyncCallback asyncCallback, Object asyncState)

```

**Comment by donutX3** [comment]
PowerController dedi ted AdminBase
