### ISSUE TITLE
Server NullReferenceExc

### ISSUE THREAD

**Issue by lukx1** [lukx1/Backupper#8]
Když je vytvořen nový tasklocation tak je hozen NullRefExc. v NewEditTaskLocationModel

Výraz házející chybu: taskLoc.Task.LastChanged = DateTime.Now;
Důvod taskLoc.Task je null
Příčina : Task nikdy není nastaven, kód:
```csharp
{
    IdTask = IdTask,
    IdSource = IdSource,
    IdDestination = IdDestination
}
```

Exception:
```csharp
System.NullReferenceException occurred
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Server.Models.Admin.NewEditTaskLocationsModel.Save() in E:\Projects\Programming\Workspace\C#\Backupper\Core\Server\Server\Models\Admin\NewEditTaskLocationsModel.cs:line 68
   at Server.Controllers.AdminTasksController.NewTaskLocation(NewEditTaskLocationsModel model) in E:\Projects\Programming\Workspace\C#\Backupper\Core\Server\Server\Controllers\AdminTasksController.cs:line 173
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<BeginInvokeSynchronousActionMethod>b__39(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()

```

**Comment by donutX3** [comment]
zpetne opraveno
